version: '3.8'
services:
  app:
    build: .
    container_name: fastapi-app
    expose:
      - "8000"  # Expose port only for internal use
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx:latest
    container_name: fastapi-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
